apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-pipeline-4
  title: Test D
  description: scaffolder action to create pipeline on azure devops
spec:
  owner: group:platform
  type: service
  parameters:
    - title: Create Pipeline
      required:
        - folder
        - repositoryName
      properties:
        folder:
          title: Folder
          type: string
          description: Folder of the pipeline
        repositoryName:
          title: Repository Name
          type: string
          description: Name of the repository
  steps:
    - id: create-pipeline
      name: Create Pipeline
      action: azuredevops:pipeline:create
      input:
        host: dev.azure.com
        name: ${{ parameters.repositoryName }}
        folder: ${{ parameters.folder }}
        project: evo-core
        organization: eshopworld
        pipelineFilePath: ./pipeline.yml
        pipelineFileType: yaml
        repositoryName: ${{ parameters.repositoryName }}
        repositoryType: azureReposGit
